In [4]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [14]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6],[12,23,34]], [[1, 2, 3], [4, 5, 6],[12,23,34]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [12 23 34]]

 [[ 1  2  3]
  [ 4  5  6]
  [12 23 34]]]


In [20]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [19]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[1, -5])

2nd element on 1st row:  6


In [21]:
import numpy as np
arr = np.array([1,2,3,4])
arr_square = arr*arr
print(arr_square)

[ 1  4  9 16]
